.gitignore, scripts/download_fgt_schema.sh, scripts/generate
Scripts to download fortigate device schema from a server.
=> scripts to download fortigate device schema

ansible_templates/code.j2, check_mode_support.txt, scripts/generate_modules.py
Add check_mode logic in code.j2
Add logic to read check_mode_suport_file
Add a new file indicating modules that have check_mode feature
=> support check_mode

ansible_templates/code.j2, ansible_templates/doc.j2, ansible_templates/examples.j2, galaxy_templates/collection/plugins/httpapi/fortios.py
Update code.j2, examples.j2 and doc.j2 files.
=> Add access token parameter in each file

ansible_templates/doc.j2
=> eprecate fortiosapi doc

special_attributes.lst
```
$cat fortios_firewall_schedule_recurring.yml
- hosts: fortigate03
connection: httpapi
collections:
- fortinet.fortios
vars:
vdom: "root"
ansible_httpapi_use_ssl: no
ansible_httpapi_validate_certs: no
ansible_httpapi_port: 80
tasks:
- name: Configure Firewall Schedule Recurring
fortios_firewall_schedule_recurring:
vdom:  "{{ vdom }}"
state: "present"
firewall_schedule_recurring:
name: 'always-TODELETE'
day:
- sunday
- monday
- tuesday
- wednesday
- thursday
- friday
- saturday
start: "00:00"
end: ""
```
result:
```
$ansible-playbook -i hosts -vvv fortios_firewall_schedule_recurring.yml
ansible-playbook 2.10.2
config file = None
configured module search path = ['/home/linky/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = …
```
=> fix https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/65

ansible_templates/code.j2, ansible_templates/doc.j2, ansible_templates/examples.j2, galaxy_templates/collection/plugins/httpapi/fortios.py, galaxy_templates/collection/plugins/module_utils/fortios/fortios.py, movable_modules.lst, scripts/generate_modules.py
To move an object  in FortiOS, issue an API request with PUT method and with `action=move&after=<>(or before=<>)` parameters.
e.g. in Ansible:
```
$cat fortios_firewall_policy.yml
- hosts: fortigate03
connection: httpapi
collections:
- fortinet.fortios
vars:
vdom: "root"
ansible_httpapi_use_ssl: yes
ansible_httpapi_validate_certs: no
ansible_httpapi_port: 443
tasks:
- name: Move Firewall Policy
fortios_firewall_policy:
vdom:  "{{ vdom }}"
access_token: "{{ fortios_access_token }}"
action: 'move'
self: 1
after: 2
```
result:
```
....
changed: [fortigate03] => {
"changed": true,
"invocation": {
"module_args": {
"access_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"action": "move",
"after": "2",
"before": null,
"firewall_policy": {
"action": null,
"anti_replay": null,
"application_list": …
```
=> support function to move objects

galaxy_templates/licence_modules/fortios_facts.py, galaxy_templates/sphinx_document/fact.rst, galaxy_templates/sphinx_document/index.rst, galaxy_templates/sphinx_document/modules.rst, galaxy_templates/sphinx_document/playbook.rst, scripts/generate_sphinx_doc
doc updates:
- top level menu structure
- fact gathering.
- playbook instructions.
+@JieX19
=> doc updates:  part 1

ansible_templates/configuration_fact.rst.j2, galaxy_templates/licence_modules/fortios_facts.py, galaxy_templates/sphinx_document/_static/collapse.css, galaxy_templates/sphinx_document/conf.py, galaxy_templates/sphinx_document/fact.rst, scripts/generate_doc.py, scripts/generate_modules.py, scripts/generate_modules_utility.py, scripts/generate_sphinx_doc
this PR is for generating `fortios_configguration_fact` sphinx document. 
note that previous generator  framework is not able to generate such a page.
@JieX19
=> doc updates:  part 2

ansible_templates/configuration_fact.rst.j2
This fixed the reverted commit which was raised to fix the traceback reverted in PR #20.
=> Sort selector into alphabetical order

galaxy_templates/licence_modules/fortios_facts.py
fix issue https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/82
=> fix construction method for legacy fortios_facts module

galaxy_templates/licence_modules/fortios_facts.py
issue https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/82
original pull request: https://github.com/fortinet-ansible-dev/fortios-ansible-generator/pull/23
=> Backport: fix construction method for legacy fortios_facts module

scripts/merge_schema.py
adding some tags
```
"system-global": {
"path": "system",
"name": "global",
"schema": {
"name": "global",
"category": "complex",
"help": "Configure global attributes.",
"children": {
"language": {
"name": "language",
"category": "unitary",
"type": "option",
"help": "GUI display language.",
"options": [
{
"name": "english",
"help": "English.",
"revisions": {
"v6.0.0": true,
"v6.2.0": true,
"v6.4.0": true
}
},
{
"name": "french",
"help": "French.",
"revisions": {
"v6.0.0": true,
"v6.2.0": true,
...
"gui-certificates": {
"name": "gui-certificates",
"category": "unitary",
"type": "option",
"help": "Enable/disable the System > Certificate GUI page, allowing you to add and configure certificates from the GUI.",
"options": [
{
"name": "enable",
"help": "Display the feature in GUI.",
"revisions": …
```
=> process schema [Work In Progress]

ansible_templates/code.j2, galaxy_templates/collection/plugins/module_utils/fortios/fortios.py, scripts/generate_modules.py
a new variable `versioned_schema ` containing versioning information is brought into code:
```
def main():
versioned_schema = {
"type": "dict",
"children": {
"dns-suffix": {
"type": "string",
"revisions": {
"v6.2.0": True,
"v6.0.0": True,
"v6.4.0": True
}
},
"ssl-insert-empty-fragment": {
"type": "string",
"options": [
{
"value": "enable",
"revisions": {
"v6.2.0": True,
"v6.0.0": True,
"v6.4.0": True
}
},
{
"value": "disable",
"revisions": {
"v6.2.0": True,
"v6.0.0": True,
"v6.4.0": True
}
}
],
"revisions": {
"v6.2.0": True,
"v6.0.0": True,
"v6.4.0": True
}
},
```
+ @JieX19
=> added versioned schema

ansible_templates/monitor_fact.j2, galaxy_templates/collection/plugins/httpapi/fortios.py, galaxy_templates/collection/plugins/module_utils/fortios/fortios.py, scripts/generate_modules.py, scripts/generate_modules_utility.py
usage:
```
- hosts: fortigate03
connection: httpapi
collections:
- fortinet.fortios
vars:
vdom: "root"
ansible_httpapi_use_ssl: yes
ansible_httpapi_validate_certs: no
ansible_httpapi_port: 443
tasks:
- name: fact gathering
fortios_monitor_fact:
vdom: "{{ vdom }}"
enable_log: true
access_token: "{{ fortios_access_token }}"
selector: 'firewall_acl'
```
=> basic fact module for monitoring APIs:code part

ansible_templates/monitor_fact.rst.j2, galaxy_templates/sphinx_document/fact.rst, scripts/generate_modules_utility.py, scripts/generate_sphinx_doc
document:
https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.0/fortios_monitor_fact.html
=> fact module for monitoring APIs: document part

galaxy_templates/collection/plugins/module_utils/fortios/fortios.py
in case the raw data instead of json formatted data is returned in FortiOS API request:
```
$cat backup.yml
- hosts: fortigate03
connection: httpapi
collections:
- fortinet.fortios
vars:
vdom: "global"
ansible_httpapi_use_ssl: yes
ansible_httpapi_validate_certs: no
ansible_httpapi_port: 443
tasks:
- name: fact gathering
fortios_monitor_fact:
vdom: "{{ vdom }}"
enable_log: true
access_token: "{{ fortios_access_token }}"
selector: 'system_config_backup'
params:
scope: vdom
```
store the raw data in `raw` field:
```
[WARNING]: selector:system_config_backup expects params:['destination(string)', 'usb_filename(string)', 'password(string)', 'vdom(string)', 'scope(string)']
ok: [fortigate03] => {
"changed": false,
"invocation": {
"module_args": {
"access_token": …
```
=> resolve raw configuration data

galaxy_templates/collection/plugins/httpapi/fortios.py
Case-insensitive for 'set-cookie'.
=> fix username/password issue in FOS7.0

ansible_templates/fact.j2, ansible_templates/monitor_fact.j2, ansible_templates/monitor_fact.rst.j2
```
- fortios_monitor_fact:
vdom: "{{ vdom }}"
enable_log: true
formatters:
- model_name
filters:
- model_name==FortiGat
selector: 'system_status'
```
=> add filtering for fortios_monitor_fact module

galaxy_templates/collection/plugins/module_utils/fortios/comparison.py
=> Fix issue in comparison

ansible_templates/code.j2, special_attributes.lst
```
- name: "Configure <system console> settings... [output]"
fortios_system_central_management:
vdom: "root"
system_central_management:
allow_monitor: "enable"
server_list:
- id:  "1"
addr_type: "ipv4"
server_address: "8.8.4.6"
server_type:
- "update"
- "rating"
```
https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/110
=> fix multiple values in system_central_management
